services:
  web:
    build:
      context: .
    container_name: django_app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8888"
    volumes:
      - ./src:/app
      - ./staticfiles:/app/staticfiles
    env_file:
      - .env
    ports:
      - "8888:8888"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_NAME: create_testcase_ai
      DATABASE_USER: root
      DATABASE_PASSWORD: Asdf1234#
      DATABASE_HOST: db
      DATABASE_PORT: 3306
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Asdf1234#
      MYSQL_DATABASE: create_testcase_ai
      MYSQL_USER: create_testcase_ai
      MYSQL_PASSWORD: Asdf1234#
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 5

  nginx:
    image: nginx:alpine
    container_name: django_app_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www/html
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - web
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    profiles: ["prod"]
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    networks:
      - app-network
    depends_on:
      - nginx
    command:
      - certonly
      - --webroot
      - --webroot-path=/var/www/certbot
      - --email=hienctt.nta@gmail.com
      - --agree-tos
      - --no-eff-email
      - -d
      - generation.nitrotech.asia

  certbot-renew:
    image: certbot/certbot
    profiles: ["prod"]
    container_name: certbot_renew
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: >
      sh -c "trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot --quiet --no-self-upgrade && nginx -s reload; sleep 12h; done"
    depends_on:
      - nginx
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge