# Generated by Django 5.1.3 on 2025-10-20 08:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_userdetail"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserDetail",
        ),
    ]
