name: CI/CD Deploy to EC2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run tests
      run: |
        if [ -f manage.py ]; then python manage.py test; fi

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Chỉ deploy khi push lên main
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Web image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/django-app:latest
        # Thêm cache để tăng tốc (tùy chọn)
        cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/django-app:latest
        cache-to: type=inline

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1  # Thay bằng region của EC2 nếu khác

    - name: Run Commands via SSM
      uses: aws-actions/amazon-ssm-send-command@v1
      with:
        instance-ids: ${{ secrets.INSTANCE_ID }}  # Thay bằng Instance ID của EC2
        document-name: AWS-RunShellScript
        parameters: |
          commands:
            - cd /home/ec2-user/testcase-generator
            - git fetch origin
            - git checkout main 2>/dev/null || git checkout -b main origin/main
            - git pull origin main
            - docker-compose down || true
            - docker-compose up -d --build
            - docker-compose exec web python manage.py migrate --noinput
            - docker-compose exec web python manage.py collectstatic --noinput
            - docker ps -a
            - docker-compose logs --tail 20
        timeout-seconds: 300  # Tùy chọn, thời gian chờ tối đa

    - name: Check SSM Command Output
      run: echo "Deployment completed via SSM"