name: CI/CD Deploy to EC2

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run tests
      run: |
        if [ -f manage.py ]; then python manage.py test; fi

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'pull_request' &&
      github.event.action == 'closed' &&
      github.event.pull_request.merged == true &&
      github.event.pull_request.base.ref == 'main' &&
      github.event.pull_request.head.ref == 'develop'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Web image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/django-app:latest
        cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/django-app:latest
        cache-to: type=inline

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy to EC2 via SSM (AWS CLI)
      id: ssm-command
      run: |
        COMMAND_ID=$(aws ssm send-command --instance-ids "${{ secrets.EC2_INSTANCE_ID }}" \
          --document-name "AWS-RunShellScript" \
          --comment "Deploy via GitHub Actions" \
          --parameters "commands=[
            \"set -e\",
            \"export HOME=/home/ec2-user\",
            \"cd /home/ec2-user/testcase-generator || { echo 'CD failed'; exit 1; }\",
            \"git config --global --add safe.directory /home/ec2-user/testcase-generator\",
            \"git config --system --add safe.directory /home/ec2-user/testcase-generator\",
            \"echo 'Current dir: $(pwd)'\",
            \"git fetch https://x-access-token:${{ secrets.TOKEN_GITHUB }}@github.com/Team-4-NTA/testcase-generator.git || { echo 'Git fetch failed'; exit 1; }\",
            \"git checkout main 2>/dev/null || git checkout -b main origin/main\",
            \"git pull https://x-access-token:${{ secrets.TOKEN_GITHUB }}@github.com/Team-4-NTA/testcase-generator.git main || { echo 'Git pull failed'; exit 1; }\",
            \"echo 'Latest commit: $(git log -1 --oneline)'\",
            \"sudo systemctl stop nginx || true\",
            \"docker-compose down || true\",
            \"docker-compose up -d --build --force-recreate\",
            \"docker-compose exec web python manage.py migrate --noinput || true\",
            \"docker-compose exec web python manage.py collectstatic --noinput || true\",
            \"docker ps -a\",
            \"docker-compose logs --tail 20 nginx\"
          ]" \
          --output text \
          --query 'Command.CommandId' \
          --timeout-seconds 600)

        echo "SSM command sent with ID: $COMMAND_ID"
        echo "command-id=$COMMAND_ID" >> $GITHUB_OUTPUT

        if [ -z "$COMMAND_ID" ]; then
          echo "Failed to get Command ID"
          exit 1
        fi

        aws ssm wait command-executed \
          --command-id "$COMMAND_ID" \
          --instance-id "${{ secrets.EC2_INSTANCE_ID }}"

    - name: Check SSM Command Status and Output
      run: |
        echo "Waiting for SSM command to complete..."

        STATUS=$(aws ssm get-command-invocation \
          --command-id "${{ steps.ssm-command.outputs.command-id }}" \
          --instance-id "${{ secrets.EC2_INSTANCE_ID }}" \
          --plugin-name "aws:runShellScript" \
          --query 'Status' \
          --output text)

        OUTPUT=$(aws ssm get-command-invocation \
          --command-id "${{ steps.ssm-command.outputs.command-id }}" \
          --instance-id "${{ secrets.EC2_INSTANCE_ID }}" \
          --plugin-name "aws:runShellScript" \
          --query 'StandardOutputContent' \
          --output text)

        ERROR=$(aws ssm get-command-invocation \
          --command-id "${{ steps.ssm-command.outputs.command-id }}" \
          --instance-id "${{ secrets.EC2_INSTANCE_ID }}" \
          --plugin-name "aws:runShellScript" \
          --query 'StandardErrorContent' \
          --output text)

        echo "Command Status: $STATUS"
        echo "SSM Output:"
        echo "$OUTPUT"
        echo "SSM Error:"
        echo "$ERROR"

        if [ "$STATUS" != "Success" ]; then
          echo "SSM command failed with status: $STATUS"
          exit 1
        fi

        echo "Deployment completed successfully via SSM."
