name: CI/CD Deploy to EC2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run tests
      run: |
        if [ -f manage.py ]; then python manage.py test; fi

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Chỉ deploy khi push lên main
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Web image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/django-app:latest
        # Thêm cache để tăng tốc (tùy chọn)
        cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/django-app:latest
        cache-to: type=inline

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1  # Thay bằng region của EC2 nếu khác

    - name: Deploy to EC2 via SSM (AWS CLI)
      run: |
        # Gửi lệnh SSM để deploy
        aws ssm send-command \
          --instance-ids "${{ secrets.AWS_REGION }}" \
          --document-name "AWS-RunShellScript" \
          --comment "Deploy via GitHub Actions" \
          --parameters "commands=[\"cd /home/ec2-user/testcase-generator\",\"git fetch origin\",\"git checkout main 2>/dev/null || git checkout -b main origin/main\",\"git pull origin main\",\"docker-compose down || true\",\"docker-compose up -d --build\",\"docker-compose exec web python manage.py migrate --noinput || true\",\"docker-compose exec web python manage.py collectstatic --noinput || true\",\"docker ps -a\",\"docker-compose logs --tail 20\"]" \
          --output text \
          --query 'Command.CommandId' \
          --timeout 300
        echo "SSM command sent successfully. Check AWS Console for output."

    - name: Check SSM Command Status
      run: |
        # Kiểm tra trạng thái lệnh SSM (tùy chọn, chờ 30 giây)
        sleep 30
        aws ssm get-command-invocation \
          --command-id "$(aws ssm list-command-invocations --command-id "$(aws ssm list-commands --filters Key=CommandId,Value=last --query 'Commands[0].CommandId' --output text)" --instance-id "${{ secrets.INSTANCE_ID }}" --query 'CommandId')" \
          --plugin-name "AWS-RunShellScript" \
          --query 'Status' \
          --output text
        echo "Deployment completed via SSM. Check logs in AWS Console for details."